---
- name:
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: checking vars
      ansible.builtin.debug:
        msg: "{{ host_name }}"

    - name: add dynamic host
      add_host:
        name: "{{ host_name }}"
        groups:
        - this_hosts

  


- name: doing the real thing
  hosts: this_hosts
  vars:
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore

  tasks:
    - name: restart spooler
      ansible.windows.win_service:
        name: "{{ service_name }}"
        state: restarted
