---
- name: tests on windows features
  gather_facts: true
  hosts: all
  
  tasks:
    - name: install on telnet client
      ansible.windows.win_feature:
        name: telnet-client
        state: absent 