---
- name: Hello World!
  hosts: all
 
  tasks:
      
  - name: Execute a command in the remote shell, stdout goes to the specified file on the remote
    ansible.builtin.win_shell: |
      get-service "{{ svc_name }}" | convertTO-json -depth 1
    register: my_out

  - debug: var=my_out.stdout_lines


