---
- name: sample shell cmd
  hosts: all

  tasks:

  - name: get resolv
    ansible.builtin.shell:
      cmd: cat /etc/resolv.conf
      
  - name: krb5
    ansible.builtin.shell:
      cmd: cat /etc/krb5.conf
      
  - name: 
    ansible.builtin.shell:
      cmd: ip a
