---
- name: restart services
  hosts: all
  gather_facts: yes
  vars:
   svc_name: spooler
   svc_names:
   - spooler
   - wuauserv
   - vss

  tasks:
    
  - name: trying loops - restart services
    ansible.windows.win_service:
     name: "{{ item }}"
     state: restarted
    loop: "{{ svc_names }}"