---
- name: restart services
  hosts: all
  gather_facts: yes
  vars:
   svc_name: spooler
   svc_names:
   - spooler
   - wuauserv
   - vss

  tasks:
  # trying loops
  - name: trying loops - restart services
    ansible.windows.win_service:
     name: "{{ item }}"
     state: restarted
    loop: "{{ svc_names }}"

  # trying when
  - name: trying when
    ansible.windows.win_service:
     name: spooler
    register: spooler_status

  - name: stop spooler when running
    ansible.builtin.shell:
     cmd: echo {{ spooler_status.stdout }}