---
- name: restart services
  hosts: all
  vars:
   svc_name: spooler
   svc_names:
   - spooler
   - winrm
   - vss

  tasks:
    
  - name: restart services
    ansible.windows.win_service:
     name: "{{ svc_name }}"
     state: restarted
    loop: "{{ svc_names }}"