---
- name: restart services
  hosts: all
  gather_facts: yes
  vars:
   svc_name: spooler
   svc_names:
   - spooler
   - wuauserv
   - vss

  tasks:
  # trying loops
  - name: trying loops - restart services
    ansible.windows.win_service:
     name: "{{ item }}"
     state: restarted
    loop: "{{ svc_names }}"

  # trying when
  - name: trying when
    ansible.windows.win_service:
     name: spooler
    register: spooler_status

  - debug: msg="{{ spooler_status }}"

  - name: stopped when spooler is running
    ansible.windows.win_service:
     name: spooler
     state: stopped
    when: spooler_status.state == running